export const EFFECTS = [
    {
        title: 'Матрица',
        value: 1378,
        info: 'Визуальный ритм – одна из главных составляющих дизайна интерьера, объединяющая общий стиль и концепцию в одно целое.',
        img_prev: './img/Matritsa_prev.png',
        img_main: './img/Matritsa_prev.png',
        price:['expensive'],
        effect: ['textured', 'pearl'],
        application: ['sleeping', 'public', 'kitchen', 'living-room', 'corridor'],
    },
    {
        title: 'Замша',
        value: 623,
        info: 'Эффект придаст тепла и уюта даже самому строгому оформлению: фактурная поверхность будет выглядеть благородно и дорого в любом оттенке, но особенно в нежных песочных и глубоких темных тонах.',
        img_prev: './img/ALCANTARA_prev.png',
        img_main: './img/ALCANTARA_main.png',
        price: ['middle'],
        effect: ['cloth', 'classic', 'imitation-fabric'],
        application: ['sleeping', 'public', 'kitchen', 'living-room', 'corridor'],    
    },
    {
        title: 'Liberty Blanche',
        value: 620,
        info: 'Эффект Liberty Blanche обращается сразу к двум древним дисциплинам: искусство и геометрия.',
        img_prev: './img/Wall_Arte_pexels_Liberty_prev.png',
        img_main: './img/Wall_Arte_pexels_Liberty_main.png',
        price: ['middle'],
        effect: ['beton', 'kamen','loft', 'metal'],
        application: ['sleeping', 'public', 'kitchen'],    
    },
    {
        title: 'Stirate',
        value: 620,
        info: 'Искусство сочетать оттенки в естественной экспрессии.',
        img_prev: './img/WALL_Arte_stirare_prev.png',
        img_main: './img/WALL_Arte_stirare_main.png',
        price: ['middle'],
        effect: ['beton', 'kamen', 'loft','metal'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Clouds',
        value: 620,
        info: 'Многие люди, находясь в напряжении и усталости, для того, чтобы отвлечься от повседневных дел, смотрят в небо. Ищите вдохновение, создавайте новые образы с эффектом Clouds',
        img_prev: './img/Image_wall_arte_15_04_prev.png',
        img_main: './img/Image_wall_arte_15_04_main.png',
        price: ['middle'],
        effect: ['beton', 'kamen', 'loft','metal'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Basamento',
        value: 4880,
        info: 'MICROCEMENT - высокопрочный декоративный материал с эффектом бетона для создания износостойких и влагостойких покрытий.',
        img_prev: './img/basamento_prev.png',
        img_main: './img/basamento_main.png',
        price:['expensive'],
        effect: ['beton', 'kamen', 'loft', 'metal'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Fortezza',
        value: 1660,
        info: 'Хотите отойти от классики и обустроить интерьер в одном из современных стилей —  используйте покрытие Microcemento, так вы сможете создать фактуру необработанного бетона и получить эффект Fortezza.',
        img_prev: './img/COLORPAVING_EPOX_STUCCO_LUCIDO_HOME_OK_prev.png',
        img_main: './img/COLORPAVING_EPOX_STUCCO_LUCIDO_HOME_OK_main.png',
        price:['expensive'],
        effect: ['beton'],
        application: ['sleeping', 'public', 'kitchen', 'living-room', 'corridor'],
    },
    {
        title: 'Замша',
        value: 995,
        info: 'Гладкая на ощупь фактурная штукатурка, благодаря сочетанию разных цветов и особого нанесения, создает неповторимый эффект “Замша”.',
        img_prev: './img/zamsha_prev.png',
        img_main: './img/zamsha_main.png',
        price: ['middle'],
        effect: ['cloth'],
        application: ['sleeping', 'living-room', 'corridor'],
    },
    {
        title: 'Марморино',
        value: 2960,
        info: 'Эффект срезанного мрамора, имитирующий полированную поверхность натурального камня. Получить данный эффект можно с помощью материала Travertino Naturale.',
        img_prev: './img/marmarino_prev.png',
        img_main: './img/marmarino_main.png',
        price:['expensive'],
        effect: ['natural'],
        application: ['sleeping', 'living-room', 'corridor'],
    },
    {
        title: 'Каррарский мрамор',
        value: 2260,
        info: 'С помощью венецианской штукатурки Decorazza Calce Veneziana вы создадите роскошный интерьер с потолками и стенами под натуральный мрамор, имитирующий дорогой природный материал.',
        img_prev: './img/karkas_mramor_prev.png',
        img_main: './img/karkas_mramor_main.png',
        price:['expensive'],
        effect: ['venetian'],
        application: ['sleeping', 'living-room', 'corridor'],
    },
    {
        title: 'Марра',
        value: 463,
        info: 'Эффект достигается с помощью материала Travertino Naturale, что позволит вам значительно преобразить жилище в величественное сооружение, напоминающее старинные памятники архитектуры.',
        img_prev: './img/mikrotsement_mikrobeton_wall2floor_novacolor_mara_prev.png',
        img_main: './img/mikrotsement_mikrobeton_wall2floor_novacolor_mara_main.png',
        price: ['cheap'],
        effect: ['beton'],
        application: ['sleeping', 'public', 'kitchen', 'living-room', 'corridor'],
    },
    {
        title: 'Mercury',
        value: 1122,
        info: 'Декоративное покрытие с эффектом Mercury поможет создать вам неординарный дизайн помещения, оно будет изысканно смотреться как в классическом интерьере городской квартиры, так и в загородном коттедже.',
        img_prev: './img/Mercury_prev.png',
        img_main: './img/Mercury_main.png',
        price:['expensive'],
        effect: ['kamen'],
        application: ['sleeping', 'living-room', 'corridor'],
    },
    {
        title: 'Лава',
        value: 1260,
        info: 'Декоративный эффект свечения “Лава”, как раскалённая вулканическая масса, добавит в интерьер элемент природной стихии.',
        img_prev: './img/Colormix_logotip_lava_prev.png',
        img_main: './img/Colormix_logotip_lava_main.png',
        price:['expensive'],
        effect: ['natural'],
        application: ['sleeping', 'living-room', 'corridor'],
    },
    {
        title: 'Hexagon',
        value: 1434,
        info: 'Декор Hexagon —  создайте в интерьере эффект шестигранной плитки.',
        img_prev: './img/Hexagon_prev.png',
        img_main: './img/Hexagon_prev.png',
        price:['expensive'],
        effect: ['stencils'],
        application: ['sleeping', 'living-room', 'corridor'],
    },
    {
        title: 'Бамбук',
        value: 1164,
        info: 'Плавные переходы тонов, успокаивающие светлые оттенки делают покрытие с эффектом «Бамбук» незаменимым для тех, кто устал от забот и ищет легкости.',
        img_prev: './img/bambuc_prev.png',
        img_main: './img/bambuc_main.png',
        price:['expensive'],
        effect: ['natural'],
        application: ['sleeping', 'living-room', 'corridor'],
    },
    {
        title: 'Мокрый шелк',
        value: 621,
        info: 'Имитация шелка на стене — идеальный выбор для тех, кто хочет создать роскошный интерьер, добавив стенам перламутровый блеск.',
        img_prev: './img/Mokryy-shelk_prev.png',
        img_main: './img/Mokryy-shelk_main.png',
        price: ['middle'],
        effect: ['silk'],
        application: ['sleeping', 'living-room', 'corridor'],
    },
    {
        title: 'Драпированный шелк',
        value: 358,
        info: 'Для формирования объемного эффекта драпированной поверхности нанесите на стену декоративную краску Velluto нужного вам оттенка. Мерцающие частицы перламутра привнесут в интерьер роскошь и благородство, характерные для классических стилей.',
        img_prev: './img/drapir_shelk_prev.png',
        img_main: './img/drapir_shelk_prev.png',
        price: ['cheap'],
        effect: ['cloth', 'silk', 'classic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Итальянский шелк',
        value: 461,
        info: 'Фактуру роскошной ткани с плавными цветовыми переходами воссоздает нанесенная абстрактными мазками, словно штукатурка, декоративная краска Seta.',
        img_prev: './img/italian_shelk_prev.png',
        img_main: './img/italian_shelk_prev.png',
        price: ['cheap'],
        effect: ['cloth', 'silk', 'classic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Гладкий шелк с переходом цвета',
        value: 346,
        info: 'Для создания утонченного покрытия с имитацией шелковой ткани и переходами разных оттенков одного цвета воспользуйтесь материалом Decorazza Seta.',
        img_prev: './img/gladkiy_shelk_with_transition_prev.png',
        img_main: './img/gladkiy_shelk_with_transition_main.png',
        price: ['cheap'],
        effect: ['cloth', 'silk', 'classic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Гладкий шелк',
        value: 358,
        info: 'Для создания декора, напоминающего муаровый шелк, нанесите легкими мазками краску Decorazza с мерцающими частицами.',
        img_prev: './img/gladkiy_shelk_prev.png',
        img_main: './img/gladkiy_shelk_main.png',
        price: ['cheap'],
        effect: ['cloth', 'silk', 'classic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Жатый шелк',
        value: 358,
        info: 'В зависимости от используемого цвета материала Seta можно создать образ  спокойного моря, песчаного берега или предгрозового неба.',
        img_prev: './img/zhatiy_shelk_prev.png',
        img_main: './img/zhatiy_shelk_main.png',
        price: ['cheap'],
        effect: ['cloth','silk', 'classic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Жатый шелк с переходом цвета',
        value: 373,
        info: 'Придает визуальную глубину помещению. Для формирования нужного настроения достаточно выбрать правильный оттенок материала Seta.',
        img_prev: './img/shatiy_shelk_with_transition_prev.png',
        img_main: './img/shatiy_shelk_with_transition_main.png',
        price: ['cheap'],
        effect: ['cloth', 'silk', 'classic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Матовый гладкий шелк',
        value: 358,
        info: 'Утонченный матовый декор без глянцевого блеска, формируемый при помощи материала Velluto, привносит уют и гармонию в помещение.',
        img_prev: './img/matoviy_shelk_prev.png',
        img_main: './img/matoviy_shelk_main.png',
        price: ['cheap'],
        effect: ['cloth', 'silk', 'classic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Матовый драпированный шелк',
        value: 358,
        info: 'Для создания аристократичного рисунка, напоминающего изысканную драпировку шелковой тканью, используйте продукт Velluto.',
        img_prev: './img/matoviy_drapirovanniy_shelk_prev.png',
        img_main: './img/matoviy_drapirovanniy_shelk_main.png',
        price: ['cheap'],
        effect: ['cloth', 'silk', 'classic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Old brick',
        value: 929,
        info: 'Эффект старой кирпичной кладки придает брутальности интерьеру, добавляет бунтарского духа или настраивает на деловой лад в зависимости от доминирующего стиля. Сформировать нужный рисунок поможет декоративная штукатурка Travertino Naturale и покрытие Pastello Vernici.',
        img_prev: './img/Old_brick_prev.png',
        img_main: './img/Old_brick_main.png',
        price: ['middle'],
        effect: ['kamen', 'brick', 'loft'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Известняк',
        value: 1610,
        info: 'Слэбы, имитирующие натуральные известковые блоки, привносят благородство и подчеркивают элегантную аристократичность интерьера. Для формирования этого эффекта потребуется нанести два вида декоративной штукатурки и защитный воск.',
        img_prev: './img/izvectnyak_prev.png',
        img_main: './img/izvectnyak_main.png',
        price:['expensive'],
        effect: ['kamen', 'brick', 'classic'],
        application: ['sleeping'],
    },
    {
        title: 'White Wall',
        value: 752,
        info: 'Белая кирпичная стена стала классическим атрибутом многих современных стилей: от скандинавского до индустриального. Покрытие подходит для отделки столовых зон, кабинетов, прихожих и других помещений.',
        img_prev: './img/White_Wall_prev.png',
        img_main: './img/White_Wall_main.png',
        price: ['middle'],
        effect: ['kamen', 'brick','loft'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Римская кладка',
        value: 744,
        info: 'Декор в виде небольших каменных слэбов достоверно имитирует древнеримскую кладку из натурального камня. Подходит для придания интерьеру строгости, сдержанности и монументальности.',
        img_prev: './img/rome_kladka_prev.png',
        img_main: './img/rome_kladka_main.png',
        price: ['middle'],
        effect: ['kamen', 'brick', 'classic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Декоративный бетон',
        value: 852,
        info: 'Имитация бетонной стены с аккуратными трещинками и сколами создается за счет нанесения декоративной штукатурки Traverta и покрытия Cera Décor. Эффект уместен в жилых комнатах, офисных кабинетах, выставочных залах галерей и на других объектах.',
        img_prev: './img/decor_beton_prev.png',
        img_main: './img/decor_beton_main.png',
        price: ['middle'],
        effect: ['beton'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Shine',
        value: 1272,
        info: 'Один из самых эффектных способов выделить определенную зону в интерьере — использовать благородное покрытие с блеском и легким сиянием. Такое покрытие органично впишется в обстановку спальни или гостиной, а устойчивая к воде и загрязнениям формула позволит не ограничивать себя и применить фантазию на кухне, в столовой или даже в ванной комнате.',
        img_prev: './img/Art-Beton_Shine_prev_main.png',
        img_main: './img/Art-Beton_Shine_prev_main.png',
        price:['expensive'],
        effect: ['textured', 'beton', 'loft', 'art-beton'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Гранж бетон',
        value: 780,
        info: 'Создать эффект необработанной бетонной стены с шершавой поверхностью и едва заметными порами можно с помощью материала Traverta и лессирующего покрытия. Светлый матовый декор будет уместен в стипмпанке, гранже и других современных стилях.',
        img_prev: './img/granzg_beton_prev.png',
        img_main: './img/granzg_beton_main.png',
        price: ['middle'],
        effect: ['beton', 'loft'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Art beton',
        value: 685,
        info: 'Эффект бетонной поверхности с небольшими углублениями, создаваемый путем нанесения декоративной штукатурки Art Beton и материала Cera Décor, идеально подходит для использования в интерьерах, оформленных в стиле лофт, хай-тек и других.',
        img_prev: './img/art-beton_prev.png',
        img_main: './img/art-beton_main.png',
        price: ['middle'],
        effect: ['beton'],
        application: ['sleeping', 'public', 'kitchen', 'corridor'],
    },
    {
        title: 'Empire',
        value: 585,
        info: 'Декор со строгими широкими линиями контрастного цвета на фоне матовой бетонной поверхности идеален для помещений в стиле хай-тек, минимализм, индастриал и других. Название эффекта – отсылка к всемирно известному небоскребу Empire State Building.',
        img_prev: './img/Empire_prev.png',
        img_main: './img/Empire_main.png',
        price: ['middle'],
        effect: ['loft'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Венецианский бетон',
        value: 1294,
        info: 'Создать аскетичный, брутальный интерьер с мужским характером поможет светло-серая или черная венецианская штукатурка Stucco Veneziano в сочетании с материалами Romano и Cera di Veneziano.',
        img_prev: './img/venezian_beton_prev_main.png',
        img_main: './img/venezian_beton_prev_main.png',
        price:['expensive'],
        effect: ['beton', 'loft'],
        application: ['sleeping'],
    },
    {
        title: 'Карта мира',
        value: 802,
        info: 'Оригинальный рисунок в виде океана с островами привнесет в интерьер глубину и теплоту (при использовании матового лессирующего материала) или строгость и прохладу (при нанесении декоративной краски или защитного глянцевого покрытия).',
        img_prev: './img/map_world_prev.png',
        img_main: './img/map_world_main.png',
        price: ['middle'],
        effect: ['classic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Травертин',
        value: 675,
        info: 'Имитация натурального камня с горизонтальными полосами привносит в интерьер тепло и зрительно расширяет помещение. Чтобы подчеркнуть глубину эффекта, нанесите на декоративную штукатурку Traverta воск.',
        img_prev: './img/travertin_prev.png',
        img_main: './img/travertin_main.png',
        price: ['middle'],
        effect: ['kamen', 'natural', 'classic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Туф',
        value: 581,
        info: 'Достоверная имитация природного камня привнесет в интерьер завораживающую простоту, теплоту и благородство натурального материала. Подходит для всех лаконичных стилей интерьера.',
        img_prev: './img/tuf_prev.png',
        img_main: './img/tuf_main.png',
        price: ['middle'],
        effect: ['kamen', 'natural'],
        application: ['sleeping', 'public', 'kitchen', 'facades'],
    },
    {
        title: 'Камень',
        value: 550,
        info: 'Декор полностью повторяет фактуру натурального необработанного камня – с контрастными переходами цвета, рельефными углублениями и заглаженными выступами. Может использоваться в интерьере в стиле ар-деко, классицизм, прованс и других.',
        img_prev: './img/stone_prev.png',
        img_main: './img/stone_main.png',
        price: ['middle'],
        effect: ['kamen', 'natural', 'classic', 'ethnic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Малахит',
        value: 325,
        info: 'Венецианская декоративная штукатурка Decorazza изумрудного оттенка позволяет воссоздать атмосферу королевской роскоши. Имитация облицовки полудрагоценным камнем привносит в интерьер благородство и утонченную свежесть.',
        img_prev: './img/malaxit_prev.png',
        img_main: './img/malaxit_main.png',
        price: ['cheap'],
        effect: ['kamen', 'natural', 'classic', 'venetian'],
        application: ['sleeping'],
    },
    {
        title: 'Оникс',
        value: 619,
        info: 'Эффект облицовки поверхности полудрагоценным камнем – ониксом – с изысканным волнообразным декором формируется с помощью венецианской декоративной штукатурки.',
        img_prev: './img/oniks_prev.png',
        img_main: './img/oniks_main.png',
        price: ['middle'],
        effect: ['kamen', 'natural','classic', 'venetian'],
        application: ['sleeping'],
    },
    {
        title: 'Рустик',
        value: 740,
        info: 'Для формирования выразительного эффекта с имитацией шероховатой фактуры природного камня используйте декоративную штукатурку Rustic и лессирующее покрытие Cera Décor. Идеально подходит для интерьеров, в которых важно подчеркнуть природную естественность.',
        img_prev: './img/rustik_prev.png',
        img_main: './img/rustik_main.png',
        price: ['middle'],
        effect: ['kamen', 'natural', 'ethnic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Венецианская штукатурка',
        value: 381,
        info: 'Роскошный эффект с имитацией мягкой бархатистой поверхности создается с помощью декоративной штукатурки Stucco Veneziano.',
        img_prev: './img/venezian_shtukaturka_prev.png',
        img_main: './img/venezian_shtukaturka_main.png',
        price: ['cheap'],
        effect: ['classic', 'venetian'],
        application: ['sleeping'],
    },
    {
        title: 'Перламутровые вихри',
        value: 269,
        info: 'Динамичная отделка с перламутровыми частицами создает неповторимую атмосферу в помещении, меняющуюся в зависимости от освещения.',
        img_prev: './img/perlamutr_vixri_prev.png',
        img_main: './img/perlamutr_vixri_main.png',
        price: ['cheap'],
        effect: ['perlamutrovaya'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Перламутровые вихри с переходом цвета',
        value: 480,
        info: 'Для формирования образа, напоминающего предгрозовое небо с перламутровыми переливами, используйте два вида декоративной краски Lucetezza.',
        img_prev: './img/perlamutr_vixri_with_transition_prev.png',
        img_main: './img/perlamutr_vixri_with_transition_main.png',
        price: ['cheap'],
        effect: ['perlamutrovaya', 'natural'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Вертикальный перелив',
        value: 372,
        info: 'Стильная отделка создается с помощью покрытия Lucetezza, привносящего в интерьер природную естественность и благородство натуральных материалов.',
        img_prev: './img/vertical_pereliv_prev.png',
        img_main: './img/vertical_pereliv_main.png',
        price: ['cheap'],
        effect: ['perlamutrovaya'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Бриз',
        value: 520,
        info: 'Создать на поверхности уникальный неглубокий рисунок с имитацией легкой ряби, появившейся от дуновения ветра, помогает краска Lucetezza.',
        img_prev: './img/briz_prev.png',
        img_main: './img/briz_main.png',
        price: ['middle'],
        effect: ['perlamutrovaya', 'natural', 'classic'],
        application: ['sleeping', 'kitchen', 'living-room', 'corridor', 'nursery'],
    },
    {
        title: 'Песчаные вихри',
        value: 490,
        info: 'Декор, напоминающий нанесенные ветром песчаные барханы или натуральный камень с темными прожилками, формируется с помощью Decorazza Brezza. Как и декоративная штукатурка, материал может использоваться для отделки всех стен или для выделения отдельных зон в помещении.',
        img_prev: './img/peschanii_bixri_prev.png',
        img_main: './img/peschanii_bixri_main.png',
        price: ['cheap'],
        effect: ['mat-pesok', 'natural'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Песчаные вихри с переходом цвета',
        value: 360,
        info: 'Декор напоминает искрящиеся под солнцем песчаные барханы. Оригинальный эффект создается за счет наличия в составе краски Brezza перламутровых и матовых песчаных частиц.',
        img_prev: './img/peschanii_bixri_with_transition_prev.png',
        img_main: './img/peschanii_bixri_with_transition_main.png',
        price: ['cheap'],
        effect: ['mat-pesok', 'natural'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Ар-деко',
        value: 476,
        info: 'Для создания темной мраморной поверхности с шероховатыми вертикальными полосами серебристого цвета, зрительно увеличивающими высоту потолков и добавляющими глубину помещению, потребуется декоративная штукатурка Stucco Veneziano и защитный воск Cera di Veneziano.',
        img_prev: './img/ar-deco_prev.png',
        img_main: './img/ar-deco_main.png',
        price: ['cheap'],
        effect: ['loft', 'venetian'],
        application: ['sleeping'],
    },
    {
        title: 'Матрица Oro',
        value: 748,
        info: 'Для формирования оригинального эффекта с вертикальными полосами, визуально увеличивающими высоту помещения, используются четыре разных оттенка золота, нанесенных на декоративную штукатурку Barilievo.',
        img_prev: './img/Matritsa_ogo_prev.png',
        img_main: './img/Matritsa_ogo_main.png',
        price: ['middle'],
        effect: ['loft'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Матрица Black Argento',
        value: 246,
        info: 'Серебристые переливы материала Perla Vernici на фоне темного оттенка краски Fiora подчеркивают лаконичность и строгость вертикальных линий, созданных с помощью декоративной штукатурки Barilievo.',
        img_prev: './img/matritsa_Black_Argento_prev.png',
        img_main: './img/matritsa_Black_Argento_main.png',
        price: ['cheap'],
        effect: ['loft'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Клондайк CLASSICO',
        value: 1166,
        info: 'Декор с диагональным фактурным рисунком и пористой поверхностью подходит для отделки кабинетов, зон отдыха и других помещений. Вам понадобятся декоративная штукатурка, краски и лессирующее покрытие.',
        img_prev: './img/klondaik_CLASSICO_prev.png',
        img_main: './img/klondaik_CLASSICO_main.png',
        price:['expensive'],
        effect: ['kamen', 'natural', 'classic'],
        application: ['sleeping', 'kitchen'],
    },
    {
        title: 'Клондайк BIANCO',
        value: 1419,
        info: 'Светлый декор с серебристым блеском и приятной на ощупь фактурой идеально подходит для лаконичных интерьеров, не перегруженных мебелью. Для создания эффекта понадобятся материалы Travertino Naturale, Pastello Vernici, Seta и Lucetezza.',
        img_prev: './img/klondaik_BIANCO_prev.png',
        img_main: './img/klondaik_BIANCO_main.png',
        price:['expensive'],
        effect: ['kamen', 'natural', 'classic'],
        application: ['sleeping', 'kitchen'],
    },
    {
        title: 'Клондайк NERO',
        value: 994,
        info: 'Глубокий темный декор с яркими золотистыми линиями имитирует фактуру горных пород с вкраплениями драгоценных материалов. Для формирования эффекта потребуется декоративная штукатурка, лессирующий состав темного цвета и декоративная краска Decorazza.',
        img_prev: './img/klondaik_NERO_prev.png',
        img_main: './img/klondaik_NERO_main.png',
        price: ['middle'],
        effect: ['kamen', 'natural', 'classic'],
        application: ['sleeping', 'kitchen'],
    },
    {
        title: 'Перламутровый перелив',
        value: 207,
        info: 'Образ, придающий помещению особую выразительность и глубину за счет перламутровых частиц, формируется с помощью декоративной краски Decorazza Aretino.',
        img_prev: './img/perlamutr_pereliv_prev.png',
        img_main: './img/perlamutr_pereliv_main.png',
        price: ['cheap'],
        effect: ['perlamutrovaya'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Океания',
        value: 322,
        info: 'Глубокий выразительный эффект в виде рисунка с тропическими островами на фоне глянцевой поверхности водной глади формируется с помощью декоративной штукатурки и лессирующих покрытий.',
        img_prev: './img/okeania_prev_main.png',
        img_main: './img/okeania_prev_main.png',
        price: ['cheap'],
        effect: ['loft', 'ethnic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Хамелеон',
        value: 1600,
        info: 'Для создания оригинального, переливающегося разными цветами эффекта используется Travertino Naturale, черная лессировка Pastello Vernici и 3 оттенка материала Seta с золотой и серебристой базой.',
        img_prev: './img/xamelion_prev.png',
        img_main: './img/xamelion_main.png',
        price:['expensive'],
        effect: ['silk', 'canvas', 'loft', 'metal', 'ethnic'],
        application: ['sleeping', 'kitchen', 'living-room', 'corridor'],
    },
    {
        title: 'Вертиго',
        value: 547,
        info: 'Замысловатый головокружительный рисунок в историческом стиле на фоне темной бронзовой или более яркой золотисто-бронзовой поверхности напоминает античные узоры.',
        img_prev: './img/vertiko_prev.png',
        img_main: './img/vertiko_main.png',
        price: ['middle'],
        effect: ['loft', 'ethnic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Матрица Argento',
        value: 412,
        info: 'Неглубокий рельеф декоративной штукатурки в виде тонких вертикальных полос и светло-серая поверхность с легким серебристым сиянием создают идеальный фон для современных интерьеров.',
        img_prev: './img/matritsa_Argento_prev.png',
        img_main: './img/matritsa_Argento_main.png',
        price: ['cheap'],
        effect: ['loft'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Glam wood',
        value: 950,
        info: 'Декор создает в помещении атмосферу диско и глэм-рока с небрежным шиком и гламуром. Для воссоздания эффекта вам понадобятся декоративная штукатурка Romano, краска Fiora и лессирующий материал Perla Vernici с бронзовой и серебристой базой.',
        img_prev: './img/Glam_wood_prev.png',
        img_main: './img/Glam_wood_main.png',
        price: ['middle'],
        effect: ['loft'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: "Vello d'oro",
        value: 490,
        info: 'Для создания приковывающих взгляд акцентов в виде имитации тончайших листов серебра или золота используются металлизированная краска Effetto Metallico и фактурная декоративная штукатурка Traverta.',
        img_prev: './img/Vello_doro_prev.png',
        img_main: './img/Vello_doro_main.png',
        price: ['cheap'],
        effect: ['classic', 'metal', 'ethnic'],
        application: ['sleeping', 'public', 'kitchen', 'living-room', 'corridor', 'nursery'],
    },
    {
        title: 'Vision',
        value: 500,
        info: 'Декор с волнообразными линиями привносит в интерьер плавность и динамичность. Для добавления визуального объема и блеска на декоративную штукатурку Barilievo наносят металлизированную краску Effetto metallico.',
        img_prev: './img/Vision_prev.png',
        img_main: './img/Vision_main.png',
        price: ['middle'],
        effect: ['cloth', 'loft', 'metal'],
        application: ['sleeping', 'public', 'kitchen', 'living-room', 'corridor', 'nursery'],
    },
    {
        title: 'Velours classique',
        value: 443,
        info: 'Создать этот изысканный вид с имитацией благородного бархата под силу даже непрофессионалу. Глубокий насыщенный цвет краски подчеркивают едва заметные полуматовые отблески.',
        img_prev: './img/Velours_classique_prev.png',
        img_main: './img/Velours_classique_main.png',
        price: ['cheap'],
        effect: ['cloth','barahat', 'velour', 'classic'],
        application: ['sleeping'],
    },
    {
        title: 'Марокканская штукатурка',
        value: 522,
        info: 'Неглубокий рельеф декоративной штукатурки с утонченными цветовыми переливами станет идеальным решением для теплых интерьеров с африканскими или восточными мотивами.',
        img_prev: './img/marokko_shtukaturka_prev.png',
        img_main: './img/marokko_shtukaturka_main.png',
        price: ['middle'],
        effect: ['classic', 'ethnic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Прованс',
        value: 416,
        info: 'Легкий в нанесении декор, добавляющий объема плоским поверхностям, создается с помощью декоративной штукатурки Barilievo и материала Cera Décor. Эффект «Прованс» может использоваться при отделке интерьеров в стиле ар-деко, классицизм и прочих.',
        img_prev: './img/provance_prev.png',
        img_main: './img/provance_main.png',
        price: ['cheap'],
        effect: ['kamen', 'ethnic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Кракелюр',
        value: 375,
        info: 'Оригинальный рисунок в виде паутинки из трещин изысканно смотрится не только в классических, но и в современных интерьерах. Для формирования эффекта используйте материал Perla Vernici и лак Craquelure.',
        img_prev: './img/krakelur_prev.png',
        img_main: './img/krakelur_main.png',
        price: ['cheap'],
        effect: ['classic'],
        application: ['sleeping'],
    },
    {
        title: 'Фактурный кракелюр',
        value: 650,
        info: 'Сложный в создании эффект придаст помещению особое благородство и классический шик. Для формирования рисунка с глубокими трещинами, хаотично расположенными на поверхности, тщательно очистите поверхность от декоративной штукатурки или других материалов, а затем следуйте инструкции.',
        img_prev: './img/factura_krakelur_prev.png',
        img_main: './img/factura_krakelur_main.png',
        price: ['middle'],
        effect: ['classic'],
        application: ['sleeping'],
    },
    {
        title: 'Везувий',
        value: 605,
        info: 'Создать необычный эффект, напоминающий о непредсказуемости природной стихии, можно с помощью материала Sollievo и матового лессирующего покрытия Cera Décor.',
        img_prev: './img/vezuviy_prev.png',
        img_main: './img/vezuviy_main.png',
        price: ['middle'],
        effect: ['kamen', 'natural'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Саман',
        value: 683,
        info: 'Ярко выраженная фактура, имитирующая глиняную поверхность с добавлением соломы, украсит интерьеры в стиле прованс, кантри, рустик, шале. Вам понадобятся декоративная штукатурка Sollievo и полупрозрачный лессирующий материал.',
        img_prev: './img/saman_prev_main.png',
        img_main: './img/saman_prev_main.png',
        price: ['middle'],
        effect: ['natural', 'ethnic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Помпеи',
        value: 812,
        info: 'Светлый декор с диагональным рисунком и четко выраженной фактурой создается с использованием декоративной штукатурки Sollievo и защитного лессирующего материала Cera Décor.',
        img_prev: './img/pompei_prev.png',
        img_main: './img/pompei_main.png',
        price: ['middle'],
        effect: ['kamen', 'natural'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Морская губка',
        value: 544,
        info: 'Воссозданная с помощью декоративной штукатурки поверхность морской губки, испещренной порами разных форм, привнесет в помещение ощущение прохлады и океанской свежести.',
        img_prev: './img/sea_sponge_prev.png',
        img_main: './img/sea_sponge_main.png',
        price: ['middle'],
        effect: ['natural', 'classic', 'ethnic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Мираж',
        value: 720,
        info: 'Эффект, имитирующий патинированную медную поверхность, станет ярким акцентом в интерьере в стиле гранж или индастриал. Для формирования вертикального рисунка используйте щетку Effetto frame.',
        img_prev: './img/mirazh_prev.png',
        img_main: './img/mirazh_main.png',
        price: ['middle'],
        effect: ['loft', 'metal'],
        application: ['sleeping', 'public', 'kitchen', 'living-room', 'corridor', 'nursery'],
    },
    {
        title: 'Шале',
        value: 682,
        info: 'Фактурный декор привнесет в помещение тепло и уют, подчеркнет благородство и естественность стиля. Эффект создается путем нанесения круговыми движениями декоративной штукатурки Sollievo и защитного воска Cera Décor.',
        img_prev: './img/shale_prev.png',
        img_main: './img/shale_main.png',
        price: ['middle'],
        effect: ['natural', 'ethnic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Velours 3D',
        value: 575,
        info: 'Оригинальное трехмерное покрытие с роскошным эффектом бархата создается с помощью краски Decorazza Velours. Цветовая палитра разработана известным дизайнером Паскалем Граво.',
        img_prev: './img/Velours_3D_prev.png',
        img_main: './img/Velours_3D_main.png',
        price: ['middle'],
        effect: ['cloth', 'barahat', 'silk', 'velour', 'classic'],
        application: ['sleeping', 'living-room'],
    },
    {
        title: 'Galaxy',
        value: 740,
        info: 'Космический рисунок с концентрическими кругами и перламутровыми переливами формируется с помощью декоративной штукатурки Murales, краски Fiora и материала Perla Vernici с серебряной и бронзовой базой.',
        img_prev: './img/Galaxy_prev_main.png',
        img_main: './img/Galaxy_prev_main.png',
        price: ['middle'],
        effect: ['loft', 'metal'],
        application: ['sleeping', 'public', 'kitchen', 'living-room', 'corridor', 'nursery'],
    },
    {
        title: 'FLYING_FISH_DESIGN',
        value: 876,
        info: 'Черная глянцевая поверхность с силуэтами летучих рыб, созданная с использованием декоративной штукатурки Stucco Veneziano, идеально подходит для элитных авторских интерьеров. Декор разработан при участии известного дизайнера Наташи Шевченко.',
        img_prev: './img/FLYING_FISH_DESIGN_prev.png',
        img_main: './img/FLYING_FISH_DESIGN_main.png',
        price: ['middle'],
        effect: ['loft', 'classic', 'venetian'],
        application: ['sleeping'],
    },
    {
        title: 'Impression',
        value: 385,
        info: 'Рисунок, символизирующий динамичность и изменчивость окружающего мира, создается путем нанесения на поверхность спонтанных мазков материалом Velluto. Декор наполняет комнату творческой энергией и помогает забыть о рутинных делах.',
        img_prev: './img/Impression_prev.png',
        img_main: './img/Impression_main.png',
        price: ['cheap'],
        effect: ['barahat'],
        application: ['sleeping', 'living-room'],
    },
    {
        title: 'Оксид меди',
        value: 225,
        info: 'Имитация крашенной металлической поверхности и ржавых потеков оригинально смотрится в помещениях с искусственным светом. Эффект «Оксид меди» формируется с использованием Seta Decorazza.',
        img_prev: './img/Cu2O_prev.png',
        img_main: './img/Cu2O_main.png',
        price: ['cheap'],
        effect: ['loft', 'metal'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Перламутровый бетон',
        value: 432,
        info: 'Для создания строгой серой поверхности с оригинальными вкраплениями перламутровых частиц используется декоративная краска Seta da Vinci.',
        img_prev: './img/perlamutr_beton_prev.png',
        img_main: './img/perlamutr_beton_main.png',
        price: ['cheap'],
        effect: ['beton', 'loft'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Диагональ',
        value: 585,
        info: 'Для создания динамичного рисунка в интерьере используйте декоративный материал Aretino с вкраплениями перламутровых песчинок. Декор позволяет зрительно расширить пространство помещения, не утяжелив дизайн.',
        img_prev: './img/diagonal_prev.png',
        img_main: './img/diagonal_main.png',
        price: ['middle'],
        effect: ['perlamutrovaya'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Парча',
        value: 461,
        info: 'Для создания поверхности с эффектом благородной шелковой ткани, украшенной золотыми нитями, используйте декоративную краску с перламутровыми частицами Lucetezza.',
        img_prev: './img/parcha_prev.png',
        img_main: './img/parcha_main.png',
        price: ['cheap'],
        effect: ['cloth', 'perlamutrovaya', 'loft'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Vintage',
        value: 670,
        info: 'Высокая пластичность декоративной штукатурки Stucco Veneziano позволяет формировать узоры, напоминающие рисунок и фактуру старинных королевских гобеленов, уникальных керамических изразцов или других винтажных поверхностей.',
        img_prev: './img/Vintage_prev.png',
        img_main: './img/Vintage_main.png',
        price: ['middle'],
        effect: ['cloth', 'classic', 'ethnic', 'venetian'],
        application: ['sleeping', 'public', 'kitchen', 'living-room', 'corridor', 'nursery'],
    },
    {
        title: 'Индастриал',
        value: 757,
        info: 'Внешне простотой и строгий декор с имитацией обшивки стен металлическими листами с фактурными выступающими заклепками создается с помощью декоративной штукатурки и нескольких видов краски.',
        img_prev: './img/indastrial_prev.png',
        img_main: './img/indastrial_main.png',
        price: ['middle'],
        effect: ['loft', 'metal'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Органза',
        value: 657,
        info: 'Выразительный эффект с имитацией тончайшей ткани, сотканной из натуральных волокон, формируется с помощью декоративной штукатурки Barilievo и краски Seta.',
        img_prev: './img/organza_prev.png',
        img_main: './img/organza_main.png',
        price: ['middle'],
        effect: ['cloth', 'canvas', 'ethnic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Рогожка',
        value: 657,
        info: 'В зависимости от варианта формирования эффекта на поверхности декоративной штукатурки можно воссоздать фактуру, напоминающую тисненную бумагу или натуральную ткань с переплетенными нитями.',
        img_prev: './img/rogozghka_prev.png',
        img_main: './img/rogozghka_main.png',
        price: ['middle'],
        effect: ['cloth', 'canvas', 'natural', 'ethnic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Холст',
        value: 453,
        info: 'Для достоверной имитации рельефной поверхности холста достаточно использовать декоративную штукатурку Barilievo и лессирующее покрытие. Рисунок, напоминающий переплетение нитей, формируется щеткой Effetto frame.',
        img_prev: './img/canvas_prev.png',
        img_main: './img/canvas_main.png',
        price: ['cheap'],
        effect: ['cloth', 'canvas', 'natural', 'ethnic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Гранж',
        value: 270,
        info: 'Этот объемный эффект создает ощущение элегантной небрежности. Декор имитирует не до конца отделанную поверхность со слегка облупившейся краской или еще неотшлифованной штукатуркой.',
        img_prev: './img/grunge_prev.png',
        img_main: './img/grunge_main.png',
        price: ['cheap'],
        effect: ['loft'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'El Dorado',
        value: 1700,
        info: 'Имитацию драгоценной горной породы с характерными золотистыми переливами и шершавой фактурой можно создать с помощью декоративной штукатурки и краски.',
        img_prev: './img/El_Dorado_prev.png',
        img_main: './img/El_Dorado_main.png',
        price:['expensive'],
        effect: ['perlamutrovaya', 'kamen', 'natural', 'metal', 'ethnic'],
        application: ['sleeping', 'public', 'kitchen', 'living-room', 'corridor', 'nursery'],
    },
    {
        title: 'New wave',
        value: 1580,
        info: 'Стильный гранжевый эффект создается путем использования 4 оттенков декоративной штукатурки Travertino Naturale и лессирующего состава. Объемность поверхности придает контрастное сочетание темных и светлых оттенков, нанесенных вертикальными полосами.',
        img_prev: './img/New_wave_prev.png',
        img_main: './img/New_wave_main.png',
        price:['expensive'],
        effect: ['loft'],
        application: ['sleeping', 'public', 'kitchen', 'water', 'living-room', 'corridor', 'floor', 'nursery'],
    },
    {
        title: 'Сварные швы',
        value: 996,
        info: 'Декор в виде слегка заржавевших металлических листов, соединенных сваркой, задаст нужное настроение в интерьерах в стиле индастриал или гранж. Для формирования эффекта используйте декоративную штукатурку, краску и матовый лак Decorazza',
        img_prev: './img/wealds_prev.png',
        img_main: './img/wealds_main.png',
        price: ['middle'],
        effect: ['loft', 'metal'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Лунная пустыня',
        value: 811,
        info: 'Футуристический рисунок с неглубокими бороздками и шероховатой фактурой будет эффектно смотреться в современных интерьерах. Цветовые переходы из желто-коричневого в серо-голубой добавляют визуальную глубину декору.',
        img_prev: './img/lunar_desert_prev.png',
        img_main: './img/lunar_desert_main.png',
        price: ['middle'],
        effect: ['loft'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Опалубка',
        value: 610,
        info: 'Эффект неотшлифованной опалубки, на которой отпечатался рисунок деревянных щитов, может использоваться при отделке помещений в стиле индастриал, конструктивизм или лофт.',
        img_prev: './img/formwork_prev.png',
        img_main: './img/formwork_main.png',
        price: ['middle'],
        effect: ['beton','loft'],
        application: ['sleeping', 'public', 'kitchen', 'facades'],
    },
    {
        title: 'Акварель',
        value: 382,
        info: 'Декоративная штукатурка Murales позволяет сформировать рисунок, напоминающий полотна знаменитых художников-акварелистов. Контраст создается за счет шероховатой фактуры и сочетания разных цветов.',
        img_prev: './img/water_color_prev.png',
        img_main: './img/water_color_main.png',
        price: ['cheap'],
        effect: ['natural', 'ethnic'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Вавилон',
        value: 672,
        info: 'Эффект с имитацией металлических листов с заклепками уместен в брутальных интерьерах, в которых нужно подчеркнуть намеренную грубость и простоту декора.',
        img_prev: './img/vavilon_prev.png',
        img_main: './img/vavilon_main.png',
        price: ['middle'],
        effect: ['loft', 'metal'],
        application: ['sleeping', 'public', 'kitchen'],
    },
    {
        title: 'Тафта',
        value: 382,
        info: 'Создать достоверную имитацию плотной ткани с благородным глянцевым блеском поможет краска Fiora и декоративный лак Fleur Deco. Приглушенные оттенки привнесут в интерьер камерность.',
        img_prev: './img/tafta_prev_main.png',
        img_main: './img/tafta_prev_main.png',
        price: ['cheap'],
        effect: ['cloth'],
        application: ['sleeping', 'public', 'kitchen'],
    },

]